/*
  # Seed NAICS Codes

  Inserting common NAICS codes covering major industry sectors.
  These are the most frequently used codes in commercial insurance.
*/

INSERT INTO naics_codes (code, title, description, sector, sector_code) VALUES
('111110', 'Soybean Farming', 'Growing soybeans and producing soybean seeds', 'Agriculture', '11'),
('111120', 'Oilseed Farming', 'Growing oilseed crops except soybeans', 'Agriculture', '11'),
('111130', 'Dry Pea and Bean Farming', 'Growing dry peas, beans, and lentils', 'Agriculture', '11'),
('111140', 'Wheat Farming', 'Growing wheat and producing wheat seed', 'Agriculture', '11'),
('111150', 'Corn Farming', 'Growing corn and producing corn seed', 'Agriculture', '11'),
('111199', 'All Other Grain Farming', 'Growing grain crops not elsewhere classified', 'Agriculture', '11'),
('111211', 'Potato Farming', 'Growing potatoes or producing seed potatoes', 'Agriculture', '11'),
('111219', 'Other Vegetable Farming', 'Growing vegetables except potatoes', 'Agriculture', '11'),
('111310', 'Orange Groves', 'Growing oranges', 'Agriculture', '11'),
('111320', 'Citrus Groves', 'Growing citrus fruits except oranges', 'Agriculture', '11'),
('111331', 'Apple Orchards', 'Growing apples', 'Agriculture', '11'),
('111332', 'Grape Vineyards', 'Growing grapes or grape seeds', 'Agriculture', '11'),
('111411', 'Mushroom Production', 'Growing mushrooms', 'Agriculture', '11'),
('111419', 'Other Food Crops Grown Under Cover', 'Growing food crops under cover', 'Agriculture', '11'),
('111421', 'Nursery and Tree Production', 'Growing nursery products and trees', 'Agriculture', '11'),
('111422', 'Floriculture Production', 'Growing flowers and foliage', 'Agriculture', '11'),
('111998', 'All Other Miscellaneous Crop Farming', 'Other crop farming', 'Agriculture', '11'),
('112111', 'Beef Cattle Ranching and Farming', 'Raising cattle for beef', 'Agriculture', '11'),
('112120', 'Dairy Cattle and Milk Production', 'Dairy farming operations', 'Agriculture', '11'),
('112210', 'Hog and Pig Farming', 'Raising hogs and pigs', 'Agriculture', '11'),
('112310', 'Chicken Egg Production', 'Raising chickens for egg production', 'Agriculture', '11'),
('112320', 'Broilers and Other Meat Type Chicken Production', 'Raising chickens for meat', 'Agriculture', '11'),
('112410', 'Sheep Farming', 'Raising sheep and goats', 'Agriculture', '11'),
('112511', 'Finfish Farming and Fish Hatcheries', 'Raising finfish or operating hatcheries', 'Agriculture', '11'),
('112512', 'Shellfish Farming', 'Raising shellfish', 'Agriculture', '11'),
('113110', 'Timber Tract Operations', 'Owning or leasing timber tracts', 'Agriculture', '11'),
('113310', 'Logging', 'Cutting timber and producing rough products', 'Agriculture', '11'),
('115111', 'Cotton Ginning', 'Operating cotton gins', 'Agriculture', '11'),
('115112', 'Soil Preparation, Planting, and Cultivating', 'Plowing, cultivating, and planting crops', 'Agriculture', '11'),
('115114', 'Postharvest Crop Activities', 'Crop preparation activities after harvest', 'Agriculture', '11'),
('115116', 'Farm Management Services', 'Providing farm management services', 'Agriculture', '11'),
('115210', 'Support Activities for Animal Production', 'Support services for animal production', 'Agriculture', '11'),
('115310', 'Support Activities for Forestry', 'Support services for forestry', 'Agriculture', '11'),
('211130', 'Natural Gas Extraction', 'Operating oil and gas field properties', 'Mining', '21'),
('212111', 'Bituminous Coal and Lignite Surface Mining', 'Surface mining of coal', 'Mining', '21'),
('212210', 'Iron Ore Mining', 'Mining iron ores', 'Mining', '21'),
('212221', 'Gold Ore Mining', 'Mining gold ores', 'Mining', '21'),
('212222', 'Silver Ore Mining', 'Mining silver ores', 'Mining', '21'),
('212231', 'Lead Ore and Zinc Ore Mining', 'Mining lead and zinc ores', 'Mining', '21'),
('212311', 'Dimension Stone Mining and Quarrying', 'Mining and quarrying dimension stone', 'Mining', '21'),
('212312', 'Crushed and Broken Limestone Mining', 'Mining and quarrying limestone', 'Mining', '21'),
('212313', 'Crushed and Broken Granite Mining', 'Mining and quarrying granite', 'Mining', '21'),
('212321', 'Construction Sand and Gravel Mining', 'Mining construction sand and gravel', 'Mining', '21'),
('213111', 'Drilling Oil and Gas Wells', 'Drilling oil and gas wells', 'Mining', '21'),
('213112', 'Support Activities for Oil and Gas Operations', 'Support for oil and gas operations', 'Mining', '21'),
('221111', 'Hydroelectric Power Generation', 'Operating hydroelectric power facilities', 'Utilities', '22'),
('221112', 'Fossil Fuel Electric Power Generation', 'Operating fossil fuel power facilities', 'Utilities', '22'),
('221113', 'Nuclear Electric Power Generation', 'Operating nuclear power facilities', 'Utilities', '22'),
('221114', 'Solar Electric Power Generation', 'Operating solar power facilities', 'Utilities', '22'),
('221115', 'Wind Electric Power Generation', 'Operating wind power facilities', 'Utilities', '22'),
('221118', 'Other Electric Power Generation', 'Other electric power generation', 'Utilities', '22'),
('221121', 'Electric Bulk Power Transmission and Control', 'Operating electric power transmission', 'Utilities', '22'),
('221122', 'Electric Power Distribution', 'Operating electric power distribution', 'Utilities', '22'),
('221210', 'Natural Gas Distribution', 'Operating gas distribution systems', 'Utilities', '22'),
('221310', 'Water Supply and Irrigation Systems', 'Operating water supply systems', 'Utilities', '22'),
('221320', 'Sewage Treatment Facilities', 'Operating sewage treatment facilities', 'Utilities', '22'),
('221330', 'Steam and Air-Conditioning Supply', 'Providing steam and air conditioning', 'Utilities', '22'),
('236115', 'New Single-Family Housing Construction', 'Building single-family houses', 'Construction', '23'),
('236116', 'New Multifamily Housing Construction', 'Building multifamily residential buildings', 'Construction', '23'),
('236117', 'New Housing For-Sale Builders', 'Building and selling new houses', 'Construction', '23'),
('236118', 'Residential Remodelers', 'Remodeling residential buildings', 'Construction', '23'),
('236210', 'Industrial Building Construction', 'Constructing industrial buildings', 'Construction', '23'),
('236220', 'Commercial and Institutional Building Construction', 'Constructing commercial buildings', 'Construction', '23'),
('237110', 'Water and Sewer Line Construction', 'Constructing water and sewer lines', 'Construction', '23'),
('237120', 'Oil and Gas Pipeline Construction', 'Constructing oil and gas pipelines', 'Construction', '23'),
('237130', 'Power and Communication Line Construction', 'Constructing power lines', 'Construction', '23'),
('237210', 'Land Subdivision', 'Subdividing land into lots', 'Construction', '23'),
('237310', 'Highway, Street, and Bridge Construction', 'Constructing highways and bridges', 'Construction', '23'),
('237990', 'Other Heavy and Civil Engineering Construction', 'Other heavy construction', 'Construction', '23'),
('238110', 'Poured Concrete Foundation and Structure', 'Pouring concrete foundations', 'Construction', '23'),
('238120', 'Structural Steel and Precast Concrete', 'Erecting structural steel', 'Construction', '23'),
('238130', 'Framing Contractors', 'Building framing', 'Construction', '23'),
('238140', 'Masonry Contractors', 'Masonry work', 'Construction', '23'),
('238150', 'Glass and Glazing Contractors', 'Installing glass and glazing', 'Construction', '23'),
('238160', 'Roofing Contractors', 'Installing roofing', 'Construction', '23'),
('238170', 'Siding Contractors', 'Installing siding', 'Construction', '23'),
('238190', 'Other Foundation, Structure, and Building Exterior', 'Other exterior contractors', 'Construction', '23'),
('238210', 'Electrical Contractors', 'Electrical work', 'Construction', '23'),
('238220', 'Plumbing, Heating, and Air-Conditioning', 'Plumbing and HVAC work', 'Construction', '23'),
('238290', 'Other Building Equipment Contractors', 'Other equipment contractors', 'Construction', '23'),
('238310', 'Drywall and Insulation Contractors', 'Drywall and insulation', 'Construction', '23'),
('238320', 'Painting and Wall Covering Contractors', 'Painting contractors', 'Construction', '23'),
('238330', 'Flooring Contractors', 'Installing flooring', 'Construction', '23'),
('238340', 'Tile and Terrazzo Contractors', 'Tile and terrazzo work', 'Construction', '23'),
('238350', 'Finish Carpentry Contractors', 'Finish carpentry', 'Construction', '23'),
('238390', 'Other Building Finishing Contractors', 'Other finishing contractors', 'Construction', '23'),
('238910', 'Site Preparation Contractors', 'Site preparation work', 'Construction', '23'),
('238990', 'All Other Specialty Trade Contractors', 'Other specialty contractors', 'Construction', '23'),
('311111', 'Dog and Cat Food Manufacturing', 'Manufacturing pet food', 'Manufacturing', '31'),
('311119', 'Other Animal Food Manufacturing', 'Other animal food manufacturing', 'Manufacturing', '31'),
('311211', 'Flour Milling', 'Milling flour from grain', 'Manufacturing', '31'),
('311224', 'Soybean and Other Oilseed Processing', 'Processing soybeans', 'Manufacturing', '31'),
('311225', 'Fats and Oils Refining and Blending', 'Refining fats and oils', 'Manufacturing', '31'),
('311230', 'Breakfast Cereal Manufacturing', 'Manufacturing breakfast cereal', 'Manufacturing', '31'),
('311313', 'Beet Sugar Manufacturing', 'Manufacturing beet sugar', 'Manufacturing', '31'),
('311314', 'Cane Sugar Manufacturing', 'Manufacturing cane sugar', 'Manufacturing', '31'),
('311340', 'Nonchocolate Confectionery Manufacturing', 'Manufacturing candy', 'Manufacturing', '31'),
('311351', 'Chocolate and Confectionery Manufacturing', 'Manufacturing chocolate', 'Manufacturing', '31'),
('311411', 'Frozen Fruit and Vegetable Manufacturing', 'Freezing fruits and vegetables', 'Manufacturing', '31'),
('311412', 'Frozen Specialty Food Manufacturing', 'Manufacturing frozen foods', 'Manufacturing', '31'),
('311421', 'Fruit and Vegetable Canning', 'Canning fruits and vegetables', 'Manufacturing', '31'),
('311423', 'Dried and Dehydrated Food Manufacturing', 'Drying foods', 'Manufacturing', '31'),
('311511', 'Fluid Milk Manufacturing', 'Manufacturing fluid milk products', 'Manufacturing', '31'),
('311512', 'Creamery Butter Manufacturing', 'Manufacturing butter', 'Manufacturing', '31'),
('311513', 'Cheese Manufacturing', 'Manufacturing cheese', 'Manufacturing', '31'),
('311514', 'Dry, Condensed, and Evaporated Dairy', 'Manufacturing dry dairy', 'Manufacturing', '31'),
('311520', 'Ice Cream and Frozen Dessert Manufacturing', 'Manufacturing ice cream', 'Manufacturing', '31'),
('311611', 'Animal Slaughtering', 'Slaughtering animals', 'Manufacturing', '31'),
('311612', 'Meat Processed from Carcasses', 'Processing meat', 'Manufacturing', '31'),
('311613', 'Rendering and Meat Byproduct Processing', 'Processing meat byproducts', 'Manufacturing', '31'),
('311615', 'Poultry Processing', 'Processing poultry', 'Manufacturing', '31'),
('311710', 'Seafood Product Preparation and Packaging', 'Processing seafood', 'Manufacturing', '31'),
('311811', 'Retail Bakeries', 'Operating retail bakeries', 'Manufacturing', '31'),
('311812', 'Commercial Bakeries', 'Operating commercial bakeries', 'Manufacturing', '31'),
('311813', 'Frozen Cakes, Pies, and Other Pastries', 'Manufacturing frozen baked goods', 'Manufacturing', '31'),
('311821', 'Cookie and Cracker Manufacturing', 'Manufacturing cookies and crackers', 'Manufacturing', '31'),
('311824', 'Dry Pasta, Dough, and Flour Mixes', 'Manufacturing pasta and dough', 'Manufacturing', '31'),
('311830', 'Tortilla Manufacturing', 'Manufacturing tortillas', 'Manufacturing', '31'),
('311911', 'Roasted Nuts and Peanut Butter', 'Manufacturing nut products', 'Manufacturing', '31'),
('311919', 'Other Snack Food Manufacturing', 'Manufacturing snack foods', 'Manufacturing', '31'),
('311920', 'Coffee and Tea Manufacturing', 'Manufacturing coffee and tea', 'Manufacturing', '31'),
('311930', 'Flavoring Syrup and Concentrate Manufacturing', 'Manufacturing flavorings', 'Manufacturing', '31'),
('311941', 'Mayonnaise, Dressing, and Sauce Manufacturing', 'Manufacturing condiments', 'Manufacturing', '31'),
('311942', 'Spice and Extract Manufacturing', 'Manufacturing spices', 'Manufacturing', '31'),
('311991', 'Perishable Prepared Food Manufacturing', 'Manufacturing prepared foods', 'Manufacturing', '31'),
('311999', 'All Other Miscellaneous Food Manufacturing', 'Other food manufacturing', 'Manufacturing', '31'),
('312111', 'Soft Drink Manufacturing', 'Manufacturing soft drinks', 'Manufacturing', '31'),
('312112', 'Bottled Water Manufacturing', 'Manufacturing bottled water', 'Manufacturing', '31'),
('312113', 'Ice Manufacturing', 'Manufacturing ice', 'Manufacturing', '31'),
('312120', 'Breweries', 'Brewing beer and ale', 'Manufacturing', '31'),
('312130', 'Wineries', 'Manufacturing wine', 'Manufacturing', '31'),
('312140', 'Distilleries', 'Manufacturing distilled spirits', 'Manufacturing', '31'),
('312230', 'Tobacco Manufacturing', 'Manufacturing tobacco products', 'Manufacturing', '31'),
('423110', 'Automobile and Other Motor Vehicle Wholesalers', 'Wholesaling motor vehicles', 'Wholesale Trade', '42'),
('423120', 'Motor Vehicle Supplies and Parts Wholesalers', 'Wholesaling auto parts', 'Wholesale Trade', '42'),
('423210', 'Furniture Merchant Wholesalers', 'Wholesaling furniture', 'Wholesale Trade', '42'),
('423310', 'Lumber and Wood Merchant Wholesalers', 'Wholesaling lumber', 'Wholesale Trade', '42'),
('423320', 'Brick, Stone, and Related Merchant Wholesalers', 'Wholesaling construction materials', 'Wholesale Trade', '42'),
('423390', 'Other Construction Material Merchant Wholesalers', 'Wholesaling other construction materials', 'Wholesale Trade', '42'),
('423410', 'Photographic Equipment Merchant Wholesalers', 'Wholesaling photographic equipment', 'Wholesale Trade', '42'),
('423420', 'Office Equipment Merchant Wholesalers', 'Wholesaling office equipment', 'Wholesale Trade', '42'),
('423430', 'Computer and Peripheral Equipment Wholesalers', 'Wholesaling computers', 'Wholesale Trade', '42'),
('423440', 'Other Commercial Equipment Merchant Wholesalers', 'Wholesaling commercial equipment', 'Wholesale Trade', '42'),
('423450', 'Medical Equipment Merchant Wholesalers', 'Wholesaling medical equipment', 'Wholesale Trade', '42'),
('423460', 'Ophthalmic Goods Merchant Wholesalers', 'Wholesaling ophthalmic goods', 'Wholesale Trade', '42'),
('423490', 'Other Professional Equipment Merchant Wholesalers', 'Wholesaling professional equipment', 'Wholesale Trade', '42'),
('423510', 'Metal Service Centers and Other Metal Wholesalers', 'Wholesaling metals', 'Wholesale Trade', '42'),
('423520', 'Coal and Other Mineral Merchant Wholesalers', 'Wholesaling coal and minerals', 'Wholesale Trade', '42'),
('423610', 'Electrical Apparatus Merchant Wholesalers', 'Wholesaling electrical equipment', 'Wholesale Trade', '42'),
('423620', 'Household Appliances Merchant Wholesalers', 'Wholesaling household appliances', 'Wholesale Trade', '42'),
('423690', 'Other Electronic Parts Merchant Wholesalers', 'Wholesaling electronic parts', 'Wholesale Trade', '42'),
('423710', 'Hardware Merchant Wholesalers', 'Wholesaling hardware', 'Wholesale Trade', '42'),
('423720', 'Plumbing Equipment Merchant Wholesalers', 'Wholesaling plumbing equipment', 'Wholesale Trade', '42'),
('423730', 'Heating Equipment Merchant Wholesalers', 'Wholesaling heating equipment', 'Wholesale Trade', '42'),
('423740', 'Refrigeration Equipment Merchant Wholesalers', 'Wholesaling refrigeration equipment', 'Wholesale Trade', '42'),
('423810', 'Construction Equipment Merchant Wholesalers', 'Wholesaling construction equipment', 'Wholesale Trade', '42'),
('423820', 'Farm and Garden Machinery Merchant Wholesalers', 'Wholesaling farm equipment', 'Wholesale Trade', '42'),
('423830', 'Industrial Machinery Merchant Wholesalers', 'Wholesaling industrial machinery', 'Wholesale Trade', '42'),
('423840', 'Industrial Supplies Merchant Wholesalers', 'Wholesaling industrial supplies', 'Wholesale Trade', '42'),
('423850', 'Service Establishment Equipment Wholesalers', 'Wholesaling service equipment', 'Wholesale Trade', '42'),
('423860', 'Transportation Equipment Merchant Wholesalers', 'Wholesaling transportation equipment', 'Wholesale Trade', '42'),
('423910', 'Sporting Goods Merchant Wholesalers', 'Wholesaling sporting goods', 'Wholesale Trade', '42'),
('423920', 'Toy and Hobby Goods Merchant Wholesalers', 'Wholesaling toys', 'Wholesale Trade', '42'),
('423930', 'Recyclable Material Merchant Wholesalers', 'Wholesaling recyclables', 'Wholesale Trade', '42'),
('423940', 'Jewelry Merchant Wholesalers', 'Wholesaling jewelry', 'Wholesale Trade', '42'),
('424110', 'Printing and Writing Paper Merchant Wholesalers', 'Wholesaling paper', 'Wholesale Trade', '42'),
('424120', 'Stationery and Office Supplies Wholesalers', 'Wholesaling office supplies', 'Wholesale Trade', '42'),
('424130', 'Industrial and Personal Service Paper Wholesalers', 'Wholesaling industrial paper', 'Wholesale Trade', '42'),
('424210', 'Drugs and Sundries Merchant Wholesalers', 'Wholesaling drugs', 'Wholesale Trade', '42'),
('424310', 'Piece Goods and Notions Merchant Wholesalers', 'Wholesaling piece goods', 'Wholesale Trade', '42'),
('424320', 'Clothing Merchant Wholesalers', 'Wholesaling clothing', 'Wholesale Trade', '42'),
('424330', 'Footwear Merchant Wholesalers', 'Wholesaling footwear', 'Wholesale Trade', '42'),
('424410', 'General Line Grocery Merchant Wholesalers', 'Wholesaling groceries', 'Wholesale Trade', '42'),
('424420', 'Packaged Frozen Food Merchant Wholesalers', 'Wholesaling frozen foods', 'Wholesale Trade', '42'),
('424430', 'Dairy Product Merchant Wholesalers', 'Wholesaling dairy products', 'Wholesale Trade', '42'),
('424440', 'Poultry and Poultry Product Wholesalers', 'Wholesaling poultry', 'Wholesale Trade', '42'),
('424450', 'Confectionery Merchant Wholesalers', 'Wholesaling confectionery', 'Wholesale Trade', '42'),
('424460', 'Fish and Seafood Merchant Wholesalers', 'Wholesaling seafood', 'Wholesale Trade', '42'),
('424470', 'Meat and Meat Product Merchant Wholesalers', 'Wholesaling meat', 'Wholesale Trade', '42'),
('424480', 'Fresh Fruit and Vegetable Merchant Wholesalers', 'Wholesaling produce', 'Wholesale Trade', '42'),
('424490', 'Other Grocery and Related Products Wholesalers', 'Wholesaling other grocery items', 'Wholesale Trade', '42'),
('424510', 'Grain and Field Bean Merchant Wholesalers', 'Wholesaling grain', 'Wholesale Trade', '42'),
('424520', 'Livestock Merchant Wholesalers', 'Wholesaling livestock', 'Wholesale Trade', '42'),
('424610', 'Plastics Materials Merchant Wholesalers', 'Wholesaling plastics', 'Wholesale Trade', '42'),
('424690', 'Other Chemical Merchant Wholesalers', 'Wholesaling chemicals', 'Wholesale Trade', '42'),
('424710', 'Petroleum Bulk Stations and Terminals', 'Operating petroleum terminals', 'Wholesale Trade', '42'),
('424720', 'Petroleum and Products Wholesalers', 'Wholesaling petroleum', 'Wholesale Trade', '42'),
('424810', 'Beer and Ale Merchant Wholesalers', 'Wholesaling beer', 'Wholesale Trade', '42'),
('424820', 'Wine and Distilled Alcoholic Beverage Wholesalers', 'Wholesaling wine and spirits', 'Wholesale Trade', '42'),
('424910', 'Farm Supplies Merchant Wholesalers', 'Wholesaling farm supplies', 'Wholesale Trade', '42'),
('424920', 'Book and Magazine Merchant Wholesalers', 'Wholesaling books', 'Wholesale Trade', '42'),
('424930', 'Flower and Nursery Stock Merchant Wholesalers', 'Wholesaling flowers', 'Wholesale Trade', '42'),
('424940', 'Tobacco and Tobacco Product Wholesalers', 'Wholesaling tobacco', 'Wholesale Trade', '42'),
('424950', 'Paint and Varnish Merchant Wholesalers', 'Wholesaling paint', 'Wholesale Trade', '42'),
('424990', 'Other Miscellaneous Nondurable Goods Wholesalers', 'Wholesaling other goods', 'Wholesale Trade', '42'),
('441110', 'New Car Dealers', 'Selling new automobiles', 'Retail Trade', '44'),
('441120', 'Used Car Dealers', 'Selling used automobiles', 'Retail Trade', '44'),
('441210', 'Recreational Vehicle Dealers', 'Selling recreational vehicles', 'Retail Trade', '44'),
('441228', 'Motorcycle, ATV, and Personal Watercraft Dealers', 'Selling motorcycles', 'Retail Trade', '44'),
('441310', 'Automotive Parts and Accessories Retailers', 'Selling auto parts', 'Retail Trade', '44'),
('441320', 'Tire Dealers', 'Selling tires', 'Retail Trade', '44'),
('442110', 'Furniture Stores', 'Selling furniture', 'Retail Trade', '44'),
('442210', 'Floor Covering Stores', 'Selling floor coverings', 'Retail Trade', '44'),
('442291', 'Window Treatment Stores', 'Selling window treatments', 'Retail Trade', '44'),
('442299', 'All Other Home Furnishings Stores', 'Selling home furnishings', 'Retail Trade', '44'),
('443141', 'Household Appliance Stores', 'Selling appliances', 'Retail Trade', '44'),
('443142', 'Electronics Stores', 'Selling electronics', 'Retail Trade', '44'),
('444110', 'Home Centers', 'Operating home centers', 'Retail Trade', '44'),
('444120', 'Paint and Wallpaper Stores', 'Selling paint', 'Retail Trade', '44'),
('444130', 'Hardware Stores', 'Operating hardware stores', 'Retail Trade', '44'),
('444190', 'Other Building Material Dealers', 'Selling building materials', 'Retail Trade', '44'),
('444210', 'Outdoor Power Equipment Stores', 'Selling outdoor equipment', 'Retail Trade', '44'),
('444220', 'Nursery and Garden Supply Stores', 'Selling garden supplies', 'Retail Trade', '44'),
('445110', 'Supermarkets and Grocery Stores', 'Operating grocery stores', 'Retail Trade', '44'),
('445120', 'Convenience Stores', 'Operating convenience stores', 'Retail Trade', '44'),
('445210', 'Meat Markets', 'Operating meat markets', 'Retail Trade', '44'),
('445220', 'Fish and Seafood Markets', 'Operating seafood markets', 'Retail Trade', '44'),
('445230', 'Fruit and Vegetable Markets', 'Operating produce markets', 'Retail Trade', '44'),
('445291', 'Baked Goods Stores', 'Operating bakery stores', 'Retail Trade', '44'),
('445292', 'Confectionery and Nut Stores', 'Operating candy stores', 'Retail Trade', '44'),
('445299', 'All Other Specialty Food Stores', 'Operating specialty food stores', 'Retail Trade', '44'),
('445310', 'Beer, Wine, and Liquor Stores', 'Selling alcoholic beverages', 'Retail Trade', '44'),
('449110', 'Furniture Stores', 'Operating furniture stores', 'Retail Trade', '44'),
('449121', 'Floor Covering Stores', 'Operating floor covering stores', 'Retail Trade', '44'),
('449122', 'Window Treatment Stores', 'Operating window treatment stores', 'Retail Trade', '44'),
('449129', 'All Other Home Furnishings Stores', 'Operating home furnishing stores', 'Retail Trade', '44'),
('449210', 'Electronics and Appliance Stores', 'Operating electronics stores', 'Retail Trade', '44'),
('452210', 'Department Stores', 'Operating department stores', 'Retail Trade', '45'),
('452311', 'Warehouse Clubs and Supercenters', 'Operating warehouse clubs', 'Retail Trade', '45'),
('452319', 'All Other General Merchandise Stores', 'Operating general merchandise stores', 'Retail Trade', '45'),
('453110', 'Florists', 'Operating florist shops', 'Retail Trade', '45'),
('453210', 'Office Supplies and Stationery Stores', 'Selling office supplies', 'Retail Trade', '45'),
('453220', 'Gift, Novelty, and Souvenir Stores', 'Selling gifts and novelties', 'Retail Trade', '45'),
('453310', 'Used Merchandise Stores', 'Selling used merchandise', 'Retail Trade', '45'),
('453910', 'Pet and Pet Supplies Stores', 'Selling pet supplies', 'Retail Trade', '45'),
('453920', 'Art Dealers', 'Selling art', 'Retail Trade', '45'),
('453930', 'Manufactured Home Dealers', 'Selling manufactured homes', 'Retail Trade', '45'),
('453991', 'Tobacco Stores', 'Selling tobacco products', 'Retail Trade', '45'),
('453998', 'All Other Miscellaneous Store Retailers', 'Operating other retail stores', 'Retail Trade', '45'),
('481111', 'Scheduled Passenger Air Transportation', 'Scheduled passenger airlines', 'Transportation', '48'),
('481112', 'Scheduled Freight Air Transportation', 'Scheduled freight airlines', 'Transportation', '48'),
('481211', 'Nonscheduled Chartered Passenger Air', 'Charter passenger airlines', 'Transportation', '48'),
('481212', 'Nonscheduled Chartered Freight Air', 'Charter freight airlines', 'Transportation', '48'),
('481219', 'Other Nonscheduled Air Transportation', 'Other air transportation', 'Transportation', '48'),
('482111', 'Line-Haul Railroads', 'Operating railroads', 'Transportation', '48'),
('482112', 'Short Line Railroads', 'Operating short line railroads', 'Transportation', '48'),
('483111', 'Deep Sea Freight Transportation', 'Deep sea shipping', 'Transportation', '48'),
('483112', 'Deep Sea Passenger Transportation', 'Deep sea passenger ships', 'Transportation', '48'),
('483113', 'Coastal and Great Lakes Freight', 'Coastal freight shipping', 'Transportation', '48'),
('483114', 'Coastal and Great Lakes Passenger', 'Coastal passenger ships', 'Transportation', '48'),
('483211', 'Inland Water Freight Transportation', 'Inland water freight', 'Transportation', '48'),
('483212', 'Inland Water Passenger Transportation', 'Inland water passenger', 'Transportation', '48'),
('484110', 'General Freight Trucking, Local', 'Local trucking', 'Transportation', '48'),
('484121', 'General Freight Trucking, Long-Distance, Truckload', 'Long-haul trucking truckload', 'Transportation', '48'),
('484122', 'General Freight Trucking, Long-Distance, LTL', 'Long-haul trucking LTL', 'Transportation', '48'),
('484210', 'Used Household and Office Goods Moving', 'Moving services', 'Transportation', '48'),
('484220', 'Specialized Freight Trucking, Local', 'Local specialized trucking', 'Transportation', '48'),
('484230', 'Specialized Freight Trucking, Long-Distance', 'Long-haul specialized trucking', 'Transportation', '48'),
('485111', 'Mixed Mode Transit Systems', 'Operating transit systems', 'Transportation', '48'),
('485112', 'Commuter Rail Systems', 'Operating commuter rail', 'Transportation', '48'),
('485113', 'Bus and Other Motor Vehicle Transit', 'Operating bus transit', 'Transportation', '48'),
('485119', 'Other Urban Transit Systems', 'Other urban transit', 'Transportation', '48'),
('485210', 'Interurban and Rural Bus Transportation', 'Interurban bus service', 'Transportation', '48'),
('485310', 'Taxi and Ridesharing Services', 'Taxi and rideshare services', 'Transportation', '48'),
('485320', 'Limousine Service', 'Limousine services', 'Transportation', '48'),
('485410', 'School and Employee Bus Transportation', 'School bus services', 'Transportation', '48'),
('485510', 'Charter Bus Industry', 'Charter bus services', 'Transportation', '48'),
('485991', 'Special Needs Transportation', 'Special needs transport', 'Transportation', '48'),
('485999', 'All Other Transit and Ground Passenger', 'Other ground transport', 'Transportation', '48'),
('486110', 'Pipeline Transportation of Crude Oil', 'Crude oil pipelines', 'Transportation', '48'),
('486210', 'Pipeline Transportation of Natural Gas', 'Natural gas pipelines', 'Transportation', '48'),
('486910', 'Pipeline Transportation of Refined Petroleum', 'Refined petroleum pipelines', 'Transportation', '48'),
('486990', 'All Other Pipeline Transportation', 'Other pipelines', 'Transportation', '48'),
('487110', 'Scenic and Sightseeing Transportation, Land', 'Land sightseeing', 'Transportation', '48'),
('487210', 'Scenic and Sightseeing Transportation, Water', 'Water sightseeing', 'Transportation', '48'),
('487990', 'Scenic and Sightseeing Transportation, Other', 'Other sightseeing', 'Transportation', '48'),
('488111', 'Air Traffic Control', 'Air traffic control', 'Transportation', '48'),
('488119', 'Other Airport Operations', 'Other airport operations', 'Transportation', '48'),
('488190', 'Other Support Activities for Air Transportation', 'Air transport support', 'Transportation', '48'),
('488210', 'Support Activities for Rail Transportation', 'Rail transport support', 'Transportation', '48'),
('488310', 'Port and Harbor Operations', 'Port operations', 'Transportation', '48'),
('488320', 'Marine Cargo Handling', 'Marine cargo handling', 'Transportation', '48'),
('488330', 'Navigational Services to Shipping', 'Navigation services', 'Transportation', '48'),
('488390', 'Other Support Activities for Water Transportation', 'Water transport support', 'Transportation', '48'),
('488410', 'Motor Vehicle Towing', 'Towing services', 'Transportation', '48'),
('488490', 'Other Support Activities for Road Transportation', 'Road transport support', 'Transportation', '48'),
('488510', 'Freight Transportation Arrangement', 'Freight brokers', 'Transportation', '48'),
('488991', 'Packing and Crating', 'Packing services', 'Transportation', '48'),
('488999', 'All Other Support Activities for Transportation', 'Other transport support', 'Transportation', '48'),
('492110', 'Couriers and Express Delivery Services', 'Courier services', 'Transportation', '48'),
('492210', 'Local Messengers and Local Delivery', 'Local delivery services', 'Transportation', '48'),
('493110', 'General Warehousing and Storage', 'General warehousing', 'Transportation', '48'),
('493120', 'Refrigerated Warehousing and Storage', 'Cold storage', 'Transportation', '48'),
('493130', 'Farm Product Warehousing and Storage', 'Farm product storage', 'Transportation', '48'),
('493190', 'Other Warehousing and Storage', 'Other warehousing', 'Transportation', '48'),
('511110', 'Newspaper Publishers', 'Publishing newspapers', 'Information', '51'),
('511120', 'Periodical Publishers', 'Publishing periodicals', 'Information', '51'),
('511130', 'Book Publishers', 'Publishing books', 'Information', '51'),
('511140', 'Directory and Mailing List Publishers', 'Publishing directories', 'Information', '51'),
('511191', 'Greeting Card Publishers', 'Publishing greeting cards', 'Information', '51'),
('511199', 'All Other Publishers', 'Other publishing', 'Information', '51'),
('511210', 'Software Publishers', 'Publishing software', 'Information', '51'),
('512110', 'Motion Picture and Video Production', 'Producing movies and video', 'Information', '51'),
('512120', 'Motion Picture and Video Distribution', 'Distributing movies', 'Information', '51'),
('512131', 'Motion Picture Theaters', 'Operating movie theaters', 'Information', '51'),
('512191', 'Teleproduction and Other Postproduction', 'Video postproduction', 'Information', '51'),
('512199', 'Other Motion Picture and Video Industries', 'Other video industries', 'Information', '51'),
('512230', 'Music Publishers', 'Publishing music', 'Information', '51'),
('512240', 'Sound Recording Studios', 'Operating recording studios', 'Information', '51'),
('512290', 'Other Sound Recording Industries', 'Other sound recording', 'Information', '51'),
('515111', 'Radio Networks', 'Operating radio networks', 'Information', '51'),
('515112', 'Radio Stations', 'Operating radio stations', 'Information', '51'),
('515120', 'Television Broadcasting', 'Television broadcasting', 'Information', '51'),
('515210', 'Cable and Other Subscription Programming', 'Cable programming', 'Information', '51'),
('517111', 'Wired Telecommunications Carriers', 'Wired telecom carriers', 'Information', '51'),
('517112', 'Wireless Telecommunications Carriers', 'Wireless carriers', 'Information', '51'),
('517121', 'Telecommunications Resellers', 'Telecom resellers', 'Information', '51'),
('517122', 'Agents for Wireless Telecommunications', 'Wireless agents', 'Information', '51'),
('517410', 'Satellite Telecommunications', 'Satellite telecom', 'Information', '51'),
('517810', 'All Other Telecommunications', 'Other telecom', 'Information', '51'),
('517919', 'All Other Telecommunications', 'Other telecom services', 'Information', '51'),
('518210', 'Data Processing and Hosting Services', 'Data processing and hosting', 'Information', '51'),
('519110', 'News Syndicates', 'News syndication', 'Information', '51'),
('519120', 'Libraries and Archives', 'Libraries and archives', 'Information', '51'),
('519130', 'Internet Publishing and Broadcasting', 'Internet publishing', 'Information', '51'),
('519190', 'All Other Information Services', 'Other information services', 'Information', '51'),
('521110', 'Monetary Authorities-Central Bank', 'Central bank', 'Finance', '52'),
('522110', 'Commercial Banking', 'Commercial banks', 'Finance', '52'),
('522120', 'Savings Institutions', 'Savings banks', 'Finance', '52'),
('522130', 'Credit Unions', 'Credit unions', 'Finance', '52'),
('522190', 'Other Depository Credit Intermediation', 'Other banking', 'Finance', '52'),
('522210', 'Credit Card Issuing', 'Credit card issuers', 'Finance', '52'),
('522220', 'Sales Financing', 'Sales financing', 'Finance', '52'),
('522291', 'Consumer Lending', 'Consumer lenders', 'Finance', '52'),
('522292', 'Real Estate Credit', 'Real estate credit', 'Finance', '52'),
('522293', 'International Trade Financing', 'Trade financing', 'Finance', '52'),
('522294', 'Secondary Market Financing', 'Secondary market', 'Finance', '52'),
('522298', 'All Other Nondepository Credit Intermediation', 'Other credit', 'Finance', '52'),
('522310', 'Mortgage and Nonmortgage Loan Brokers', 'Loan brokers', 'Finance', '52'),
('522320', 'Financial Transactions Processing', 'Financial processing', 'Finance', '52'),
('522390', 'Other Activities Related to Credit Intermediation', 'Other credit activities', 'Finance', '52'),
('523110', 'Investment Banking and Securities Dealing', 'Investment banking', 'Finance', '52'),
('523120', 'Securities Brokerage', 'Securities brokers', 'Finance', '52'),
('523130', 'Commodity Contracts Dealing', 'Commodity dealers', 'Finance', '52'),
('523140', 'Commodity Contracts Brokerage', 'Commodity brokers', 'Finance', '52'),
('523210', 'Securities and Commodity Exchanges', 'Securities exchanges', 'Finance', '52'),
('523910', 'Miscellaneous Intermediation', 'Other financial intermediation', 'Finance', '52'),
('523920', 'Portfolio Management', 'Portfolio management', 'Finance', '52'),
('523930', 'Investment Advice', 'Investment advisors', 'Finance', '52'),
('523991', 'Trust, Fiduciary, and Custody Activities', 'Trust services', 'Finance', '52'),
('523999', 'Miscellaneous Financial Investment Activities', 'Other investment activities', 'Finance', '52'),
('524113', 'Direct Life Insurance Carriers', 'Life insurance carriers', 'Finance', '52'),
('524114', 'Direct Health Insurance Carriers', 'Health insurance carriers', 'Finance', '52'),
('524126', 'Direct Property and Casualty Insurance Carriers', 'P&C insurance carriers', 'Finance', '52'),
('524127', 'Direct Title Insurance Carriers', 'Title insurance carriers', 'Finance', '52'),
('524128', 'Other Direct Insurance Carriers', 'Other insurance carriers', 'Finance', '52'),
('524130', 'Reinsurance Carriers', 'Reinsurance carriers', 'Finance', '52'),
('524210', 'Insurance Agencies and Brokerages', 'Insurance agencies', 'Finance', '52'),
('524291', 'Claims Adjusting', 'Claims adjusters', 'Finance', '52'),
('524292', 'Third Party Administration of Insurance', 'Insurance TPA', 'Finance', '52'),
('524298', 'All Other Insurance Related Activities', 'Other insurance activities', 'Finance', '52'),
('525110', 'Pension Funds', 'Pension funds', 'Finance', '52'),
('525120', 'Health and Welfare Funds', 'Health funds', 'Finance', '52'),
('525190', 'Other Insurance Funds', 'Other insurance funds', 'Finance', '52'),
('525910', 'Open-End Investment Funds', 'Mutual funds', 'Finance', '52'),
('525920', 'Trusts, Estates, and Agency Accounts', 'Trust management', 'Finance', '52'),
('525990', 'Other Financial Vehicles', 'Other financial vehicles', 'Finance', '52'),
('531110', 'Lessors of Residential Buildings', 'Residential property lessors', 'Real Estate', '53'),
('531120', 'Lessors of Nonresidential Buildings', 'Commercial property lessors', 'Real Estate', '53'),
('531130', 'Lessors of Miniwarehouses and Self-Storage', 'Self-storage operators', 'Real Estate', '53'),
('531190', 'Lessors of Other Real Estate Property', 'Other property lessors', 'Real Estate', '53'),
('531210', 'Offices of Real Estate Agents and Brokers', 'Real estate agents', 'Real Estate', '53'),
('531311', 'Residential Property Managers', 'Residential property management', 'Real Estate', '53'),
('531312', 'Nonresidential Property Managers', 'Commercial property management', 'Real Estate', '53'),
('531320', 'Offices of Real Estate Appraisers', 'Real estate appraisers', 'Real Estate', '53'),
('531390', 'Other Activities Related to Real Estate', 'Other real estate activities', 'Real Estate', '53'),
('532111', 'Passenger Car Rental', 'Car rental', 'Rental', '53'),
('532112', 'Passenger Car Leasing', 'Car leasing', 'Rental', '53'),
('532120', 'Truck, Utility Trailer, and RV Rental and Leasing', 'Truck rental', 'Rental', '53'),
('532210', 'Consumer Electronics and Appliances Rental', 'Electronics rental', 'Rental', '53'),
('532281', 'Formal Wear and Costume Rental', 'Formal wear rental', 'Rental', '53'),
('532282', 'Video Tape and Disc Rental', 'Video rental', 'Rental', '53'),
('532283', 'Home Health Equipment Rental', 'Medical equipment rental', 'Rental', '53'),
('532284', 'Recreational Goods Rental', 'Recreation equipment rental', 'Rental', '53'),
('532289', 'All Other Consumer Goods Rental', 'Other consumer goods rental', 'Rental', '53'),
('532310', 'General Rental Centers', 'General rental centers', 'Rental', '53'),
('532411', 'Commercial Air, Rail, and Water Equipment Rental', 'Commercial transport rental', 'Rental', '53'),
('532412', 'Construction Equipment Rental and Leasing', 'Construction equipment rental', 'Rental', '53'),
('532420', 'Office Machinery and Equipment Rental', 'Office equipment rental', 'Rental', '53'),
('532490', 'Other Commercial Equipment Rental', 'Other commercial rental', 'Rental', '53'),
('541110', 'Offices of Lawyers', 'Law offices', 'Professional Services', '54'),
('541120', 'Offices of Notaries', 'Notary offices', 'Professional Services', '54'),
('541191', 'Title Abstract and Settlement Offices', 'Title companies', 'Professional Services', '54'),
('541199', 'All Other Legal Services', 'Other legal services', 'Professional Services', '54'),
('541211', 'Offices of Certified Public Accountants', 'CPA offices', 'Professional Services', '54'),
('541213', 'Tax Preparation Services', 'Tax preparers', 'Professional Services', '54'),
('541214', 'Payroll Services', 'Payroll services', 'Professional Services', '54'),
('541219', 'Other Accounting Services', 'Other accounting services', 'Professional Services', '54'),
('541310', 'Architectural Services', 'Architectural services', 'Professional Services', '54'),
('541320', 'Landscape Architectural Services', 'Landscape architects', 'Professional Services', '54'),
('541330', 'Engineering Services', 'Engineering services', 'Professional Services', '54'),
('541340', 'Drafting Services', 'Drafting services', 'Professional Services', '54'),
('541350', 'Building Inspection Services', 'Building inspectors', 'Professional Services', '54'),
('541360', 'Geophysical Surveying and Mapping Services', 'Surveying services', 'Professional Services', '54'),
('541370', 'Surveying and Mapping Services', 'Land surveying', 'Professional Services', '54'),
('541380', 'Testing Laboratories', 'Testing labs', 'Professional Services', '54'),
('541410', 'Interior Design Services', 'Interior designers', 'Professional Services', '54'),
('541420', 'Industrial Design Services', 'Industrial designers', 'Professional Services', '54'),
('541430', 'Graphic Design Services', 'Graphic designers', 'Professional Services', '54'),
('541490', 'Other Specialized Design Services', 'Other design services', 'Professional Services', '54'),
('541511', 'Custom Computer Programming Services', 'Custom software development', 'Professional Services', '54'),
('541512', 'Computer Systems Design Services', 'Systems design', 'Professional Services', '54'),
('541513', 'Computer Facilities Management Services', 'IT management services', 'Professional Services', '54'),
('541519', 'Other Computer Related Services', 'Other IT services', 'Professional Services', '54'),
('541611', 'Administrative Management Consulting', 'Management consulting', 'Professional Services', '54'),
('541612', 'Human Resources Consulting Services', 'HR consulting', 'Professional Services', '54'),
('541613', 'Marketing Consulting Services', 'Marketing consulting', 'Professional Services', '54'),
('541614', 'Process and Logistics Consulting Services', 'Process consulting', 'Professional Services', '54'),
('541618', 'Other Management Consulting Services', 'Other consulting', 'Professional Services', '54'),
('541620', 'Environmental Consulting Services', 'Environmental consulting', 'Professional Services', '54'),
('541690', 'Other Scientific and Technical Consulting', 'Technical consulting', 'Professional Services', '54'),
('541711', 'Research and Development in Biotechnology', 'Biotech R&D', 'Professional Services', '54'),
('541712', 'Research and Development in Physical Sciences', 'Physical science R&D', 'Professional Services', '54'),
('541713', 'Research and Development in Nanotechnology', 'Nanotech R&D', 'Professional Services', '54'),
('541714', 'Research and Development in Engineering', 'Engineering R&D', 'Professional Services', '54'),
('541715', 'Research and Development in Life Sciences', 'Life science R&D', 'Professional Services', '54'),
('541720', 'Research and Development in Social Sciences', 'Social science R&D', 'Professional Services', '54'),
('541810', 'Advertising Agencies', 'Advertising agencies', 'Professional Services', '54'),
('541820', 'Public Relations Agencies', 'PR agencies', 'Professional Services', '54'),
('541830', 'Media Buying Agencies', 'Media buying', 'Professional Services', '54'),
('541840', 'Media Representatives', 'Media representatives', 'Professional Services', '54'),
('541850', 'Outdoor Advertising', 'Outdoor advertising', 'Professional Services', '54'),
('541860', 'Direct Mail Advertising', 'Direct mail advertising', 'Professional Services', '54'),
('541870', 'Advertising Material Distribution Services', 'Ad material distribution', 'Professional Services', '54'),
('541890', 'Other Services Related to Advertising', 'Other advertising services', 'Professional Services', '54'),
('541910', 'Marketing Research and Public Opinion Polling', 'Market research', 'Professional Services', '54'),
('541921', 'Photography Studios, Portrait', 'Portrait photography', 'Professional Services', '54'),
('541922', 'Commercial Photography', 'Commercial photography', 'Professional Services', '54'),
('541930', 'Translation and Interpretation Services', 'Translation services', 'Professional Services', '54'),
('541940', 'Veterinary Services', 'Veterinary services', 'Professional Services', '54'),
('541990', 'All Other Professional Services', 'Other professional services', 'Professional Services', '54'),
('551111', 'Offices of Bank Holding Companies', 'Bank holding companies', 'Management', '55'),
('551112', 'Offices of Other Holding Companies', 'Other holding companies', 'Management', '55'),
('551114', 'Corporate, Subsidiary, and Regional Managing', 'Corporate offices', 'Management', '55'),
('561110', 'Office Administrative Services', 'Office admin services', 'Administrative', '56'),
('561210', 'Facilities Support Services', 'Facilities support', 'Administrative', '56'),
('561311', 'Employment Placement Agencies', 'Employment agencies', 'Administrative', '56'),
('561312', 'Executive Search Services', 'Executive search', 'Administrative', '56'),
('561320', 'Temporary Help Services', 'Temp staffing', 'Administrative', '56'),
('561330', 'Professional Employer Organizations', 'PEOs', 'Administrative', '56'),
('561410', 'Document Preparation Services', 'Document prep', 'Administrative', '56'),
('561421', 'Telephone Answering Services', 'Answering services', 'Administrative', '56'),
('561422', 'Telemarketing Bureaus and Call Centers', 'Call centers', 'Administrative', '56'),
('561431', 'Private Mail Centers', 'Mail centers', 'Administrative', '56'),
('561439', 'Other Business Service Centers', 'Business service centers', 'Administrative', '56'),
('561440', 'Collection Agencies', 'Collection agencies', 'Administrative', '56'),
('561450', 'Credit Bureaus', 'Credit bureaus', 'Administrative', '56'),
('561491', 'Repossession Services', 'Repo services', 'Administrative', '56'),
('561492', 'Court Reporting and Stenotype Services', 'Court reporters', 'Administrative', '56'),
('561499', 'All Other Business Support Services', 'Other business support', 'Administrative', '56'),
('561510', 'Travel Agencies', 'Travel agencies', 'Administrative', '56'),
('561520', 'Tour Operators', 'Tour operators', 'Administrative', '56'),
('561591', 'Convention and Visitors Bureaus', 'Convention bureaus', 'Administrative', '56'),
('561599', 'All Other Travel Arrangement Services', 'Other travel services', 'Administrative', '56'),
('561611', 'Investigation Services', 'Investigation services', 'Administrative', '56'),
('561612', 'Security Guards and Patrol Services', 'Security guards', 'Administrative', '56'),
('561613', 'Armored Car Services', 'Armored car services', 'Administrative', '56'),
('561621', 'Security Systems Services', 'Security systems', 'Administrative', '56'),
('561622', 'Locksmiths', 'Locksmiths', 'Administrative', '56'),
('561710', 'Exterminating and Pest Control Services', 'Pest control', 'Administrative', '56'),
('561720', 'Janitorial Services', 'Janitorial services', 'Administrative', '56'),
('561730', 'Landscaping Services', 'Landscaping', 'Administrative', '56'),
('561740', 'Carpet and Upholstery Cleaning Services', 'Carpet cleaning', 'Administrative', '56'),
('561790', 'Other Services to Buildings and Dwellings', 'Other building services', 'Administrative', '56'),
('561910', 'Packaging and Labeling Services', 'Packaging services', 'Administrative', '56'),
('561920', 'Convention and Trade Show Organizers', 'Convention organizers', 'Administrative', '56'),
('561990', 'All Other Support Services', 'Other support services', 'Administrative', '56'),
('562111', 'Solid Waste Collection', 'Waste collection', 'Waste Management', '56'),
('562112', 'Hazardous Waste Collection', 'Hazardous waste collection', 'Waste Management', '56'),
('562119', 'Other Waste Collection', 'Other waste collection', 'Waste Management', '56'),
('562211', 'Hazardous Waste Treatment and Disposal', 'Hazardous waste disposal', 'Waste Management', '56'),
('562212', 'Solid Waste Landfill', 'Landfill operations', 'Waste Management', '56'),
('562213', 'Solid Waste Combustors and Incinerators', 'Waste incineration', 'Waste Management', '56'),
('562219', 'Other Nonhazardous Waste Treatment', 'Other waste treatment', 'Waste Management', '56'),
('562910', 'Remediation Services', 'Environmental remediation', 'Waste Management', '56'),
('562920', 'Materials Recovery Facilities', 'Recycling facilities', 'Waste Management', '56'),
('562991', 'Septic Tank and Related Services', 'Septic services', 'Waste Management', '56'),
('562998', 'All Other Miscellaneous Waste Management', 'Other waste management', 'Waste Management', '56'),
('611110', 'Elementary and Secondary Schools', 'K-12 schools', 'Education', '61'),
('611210', 'Junior Colleges', 'Community colleges', 'Education', '61'),
('611310', 'Colleges, Universities, and Professional Schools', 'Colleges and universities', 'Education', '61'),
('611410', 'Business and Secretarial Schools', 'Business schools', 'Education', '61'),
('611420', 'Computer Training', 'Computer training', 'Education', '61'),
('611430', 'Professional and Management Development Training', 'Professional training', 'Education', '61'),
('611511', 'Cosmetology and Barber Schools', 'Cosmetology schools', 'Education', '61'),
('611512', 'Flight Training', 'Flight schools', 'Education', '61'),
('611513', 'Apprenticeship Training', 'Apprenticeship programs', 'Education', '61'),
('611519', 'Other Technical and Trade Schools', 'Trade schools', 'Education', '61'),
('611610', 'Fine Arts Schools', 'Art schools', 'Education', '61'),
('611620', 'Sports and Recreation Instruction', 'Sports instruction', 'Education', '61'),
('611630', 'Language Schools', 'Language schools', 'Education', '61'),
('611691', 'Exam Preparation and Tutoring', 'Tutoring services', 'Education', '61'),
('611692', 'Automobile Driving Schools', 'Driving schools', 'Education', '61'),
('611699', 'All Other Miscellaneous Schools and Instruction', 'Other schools', 'Education', '61'),
('611710', 'Educational Support Services', 'Education support', 'Education', '61'),
('621111', 'Offices of Physicians', 'Physician offices', 'Healthcare', '62'),
('621112', 'Offices of Physicians, Mental Health Specialists', 'Psychiatrist offices', 'Healthcare', '62'),
('621210', 'Offices of Dentists', 'Dental offices', 'Healthcare', '62'),
('621310', 'Offices of Chiropractors', 'Chiropractic offices', 'Healthcare', '62'),
('621320', 'Offices of Optometrists', 'Optometrist offices', 'Healthcare', '62'),
('621330', 'Offices of Mental Health Practitioners', 'Mental health offices', 'Healthcare', '62'),
('621340', 'Offices of Physical and Occupational Therapists', 'PT/OT offices', 'Healthcare', '62'),
('621391', 'Offices of Podiatrists', 'Podiatry offices', 'Healthcare', '62'),
('621399', 'Offices of All Other Miscellaneous Health Practitioners', 'Other health offices', 'Healthcare', '62'),
('621410', 'Family Planning Centers', 'Family planning', 'Healthcare', '62'),
('621420', 'Outpatient Mental Health Centers', 'Mental health centers', 'Healthcare', '62'),
('621491', 'HMO Medical Centers', 'HMO centers', 'Healthcare', '62'),
('621492', 'Kidney Dialysis Centers', 'Dialysis centers', 'Healthcare', '62'),
('621493', 'Freestanding Ambulatory Surgical Centers', 'Surgery centers', 'Healthcare', '62'),
('621498', 'All Other Outpatient Care Centers', 'Other outpatient care', 'Healthcare', '62'),
('621511', 'Medical Laboratories', 'Medical labs', 'Healthcare', '62'),
('621512', 'Diagnostic Imaging Centers', 'Imaging centers', 'Healthcare', '62'),
('621610', 'Home Health Care Services', 'Home health care', 'Healthcare', '62'),
('621910', 'Ambulance Services', 'Ambulance services', 'Healthcare', '62'),
('621991', 'Blood and Organ Banks', 'Blood banks', 'Healthcare', '62'),
('621999', 'All Other Miscellaneous Ambulatory Health Care', 'Other ambulatory care', 'Healthcare', '62'),
('622110', 'General Medical and Surgical Hospitals', 'General hospitals', 'Healthcare', '62'),
('622210', 'Psychiatric and Substance Abuse Hospitals', 'Psychiatric hospitals', 'Healthcare', '62'),
('622310', 'Specialty Hospitals', 'Specialty hospitals', 'Healthcare', '62'),
('623110', 'Nursing Care Facilities', 'Nursing homes', 'Healthcare', '62'),
('623210', 'Residential Intellectual and Developmental Disability', 'IDD facilities', 'Healthcare', '62'),
('623220', 'Residential Mental Health and Substance Abuse', 'Mental health residential', 'Healthcare', '62'),
('623311', 'Continuing Care Retirement Communities', 'CCRCs', 'Healthcare', '62'),
('623312', 'Assisted Living Facilities for the Elderly', 'Assisted living', 'Healthcare', '62'),
('623990', 'Other Residential Care Facilities', 'Other residential care', 'Healthcare', '62'),
('624110', 'Child and Youth Services', 'Child services', 'Social Assistance', '62'),
('624120', 'Services for the Elderly and Persons with Disabilities', 'Elder services', 'Social Assistance', '62'),
('624190', 'Other Individual and Family Services', 'Family services', 'Social Assistance', '62'),
('624210', 'Community Food Services', 'Food banks', 'Social Assistance', '62'),
('624221', 'Temporary Shelters', 'Shelters', 'Social Assistance', '62'),
('624229', 'Other Community Housing Services', 'Housing services', 'Social Assistance', '62'),
('624230', 'Emergency and Other Relief Services', 'Emergency relief', 'Social Assistance', '62'),
('624310', 'Vocational Rehabilitation Services', 'Vocational rehab', 'Social Assistance', '62'),
('624410', 'Child Day Care Services', 'Day care', 'Social Assistance', '62'),
('711110', 'Theater Companies and Dinner Theaters', 'Theater companies', 'Arts & Recreation', '71'),
('711120', 'Dance Companies', 'Dance companies', 'Arts & Recreation', '71'),
('711130', 'Musical Groups and Artists', 'Musicians', 'Arts & Recreation', '71'),
('711190', 'Other Performing Arts Companies', 'Other performing arts', 'Arts & Recreation', '71'),
('711211', 'Sports Teams and Clubs', 'Sports teams', 'Arts & Recreation', '71'),
('711212', 'Racetracks', 'Racetracks', 'Arts & Recreation', '71'),
('711219', 'Other Spectator Sports', 'Other spectator sports', 'Arts & Recreation', '71'),
('711310', 'Promoters of Performing Arts and Sports with Facilities', 'Event promoters with facilities', 'Arts & Recreation', '71'),
('711320', 'Promoters of Performing Arts and Sports without Facilities', 'Event promoters', 'Arts & Recreation', '71'),
('711410', 'Agents and Managers for Artists and Athletes', 'Talent agents', 'Arts & Recreation', '71'),
('711510', 'Independent Artists, Writers, and Performers', 'Independent artists', 'Arts & Recreation', '71'),
('712110', 'Museums', 'Museums', 'Arts & Recreation', '71'),
('712120', 'Historical Sites', 'Historical sites', 'Arts & Recreation', '71'),
('712130', 'Zoos and Botanical Gardens', 'Zoos and gardens', 'Arts & Recreation', '71'),
('712190', 'Nature Parks and Other Similar Institutions', 'Nature parks', 'Arts & Recreation', '71'),
('713110', 'Amusement and Theme Parks', 'Theme parks', 'Arts & Recreation', '71'),
('713120', 'Amusement Arcades', 'Arcades', 'Arts & Recreation', '71'),
('713210', 'Casinos', 'Casinos', 'Arts & Recreation', '71'),
('713290', 'Other Gambling Industries', 'Other gambling', 'Arts & Recreation', '71'),
('713910', 'Golf Courses and Country Clubs', 'Golf courses', 'Arts & Recreation', '71'),
('713920', 'Skiing Facilities', 'Ski resorts', 'Arts & Recreation', '71'),
('713930', 'Marinas', 'Marinas', 'Arts & Recreation', '71'),
('713940', 'Fitness and Recreational Sports Centers', 'Fitness centers', 'Arts & Recreation', '71'),
('713950', 'Bowling Centers', 'Bowling alleys', 'Arts & Recreation', '71'),
('713990', 'All Other Amusement and Recreation Industries', 'Other recreation', 'Arts & Recreation', '71'),
('721110', 'Hotels and Motels', 'Hotels and motels', 'Accommodation', '72'),
('721120', 'Casino Hotels', 'Casino hotels', 'Accommodation', '72'),
('721191', 'Bed-and-Breakfast Inns', 'B&Bs', 'Accommodation', '72'),
('721199', 'All Other Traveler Accommodation', 'Other lodging', 'Accommodation', '72'),
('721211', 'RV Parks and Campgrounds', 'RV parks', 'Accommodation', '72'),
('721214', 'Recreational and Vacation Camps', 'Vacation camps', 'Accommodation', '72'),
('721310', 'Rooming and Boarding Houses', 'Rooming houses', 'Accommodation', '72'),
('722310', 'Food Service Contractors', 'Food service contractors', 'Food Services', '72'),
('722320', 'Caterers', 'Catering', 'Food Services', '72'),
('722330', 'Mobile Food Services', 'Food trucks', 'Food Services', '72'),
('722410', 'Drinking Places', 'Bars', 'Food Services', '72'),
('722511', 'Full-Service Restaurants', 'Full-service restaurants', 'Food Services', '72'),
('722513', 'Limited-Service Restaurants', 'Fast food restaurants', 'Food Services', '72'),
('722514', 'Cafeterias and Buffets', 'Cafeterias', 'Food Services', '72'),
('722515', 'Snack and Nonalcoholic Beverage Bars', 'Snack bars', 'Food Services', '72'),
('811111', 'General Automotive Repair', 'Auto repair', 'Other Services', '81'),
('811112', 'Automotive Exhaust System Repair', 'Exhaust repair', 'Other Services', '81'),
('811113', 'Automotive Transmission Repair', 'Transmission repair', 'Other Services', '81'),
('811118', 'Other Automotive Mechanical and Electrical Repair', 'Other auto repair', 'Other Services', '81'),
('811121', 'Automotive Body and Interior Repair', 'Body shops', 'Other Services', '81'),
('811122', 'Automotive Glass Replacement Shops', 'Auto glass', 'Other Services', '81'),
('811191', 'Automotive Oil Change and Lubrication Shops', 'Oil change shops', 'Other Services', '81'),
('811192', 'Car Washes', 'Car washes', 'Other Services', '81'),
('811198', 'All Other Automotive Repair and Maintenance', 'Other auto maintenance', 'Other Services', '81'),
('811210', 'Electronic and Precision Equipment Repair', 'Electronics repair', 'Other Services', '81'),
('811310', 'Commercial and Industrial Equipment Repair', 'Commercial equipment repair', 'Other Services', '81'),
('811411', 'Home and Garden Equipment Repair and Maintenance', 'Home equipment repair', 'Other Services', '81'),
('811412', 'Appliance Repair and Maintenance', 'Appliance repair', 'Other Services', '81'),
('811420', 'Reupholstery and Furniture Repair', 'Furniture repair', 'Other Services', '81'),
('811430', 'Footwear and Leather Goods Repair', 'Shoe repair', 'Other Services', '81'),
('811490', 'Other Personal and Household Goods Repair', 'Other repair services', 'Other Services', '81'),
('812111', 'Barber Shops', 'Barber shops', 'Other Services', '81'),
('812112', 'Beauty Salons', 'Beauty salons', 'Other Services', '81'),
('812113', 'Nail Salons', 'Nail salons', 'Other Services', '81'),
('812191', 'Diet and Weight Reducing Centers', 'Weight loss centers', 'Other Services', '81'),
('812199', 'Other Personal Care Services', 'Other personal care', 'Other Services', '81'),
('812210', 'Funeral Homes and Funeral Services', 'Funeral homes', 'Other Services', '81'),
('812220', 'Cemeteries and Crematories', 'Cemeteries', 'Other Services', '81'),
('812310', 'Coin-Operated Laundries and Drycleaners', 'Laundromats', 'Other Services', '81'),
('812320', 'Drycleaning and Laundry Services', 'Dry cleaners', 'Other Services', '81'),
('812331', 'Linen Supply', 'Linen services', 'Other Services', '81'),
('812332', 'Industrial Launderers', 'Industrial laundry', 'Other Services', '81'),
('812910', 'Pet Care Services', 'Pet care', 'Other Services', '81'),
('812921', 'Photofinishing Laboratories', 'Photo labs', 'Other Services', '81'),
('812922', 'One-Hour Photofinishing', 'One-hour photo', 'Other Services', '81'),
('812930', 'Parking Lots and Garages', 'Parking services', 'Other Services', '81'),
('812990', 'All Other Personal Services', 'Other personal services', 'Other Services', '81'),
('813110', 'Religious Organizations', 'Churches and religious orgs', 'Membership Organizations', '81'),
('813211', 'Grantmaking Foundations', 'Foundations', 'Membership Organizations', '81'),
('813212', 'Voluntary Health Organizations', 'Health charities', 'Membership Organizations', '81'),
('813219', 'Other Grantmaking and Giving Services', 'Other charities', 'Membership Organizations', '81'),
('813311', 'Human Rights Organizations', 'Human rights orgs', 'Membership Organizations', '81'),
('813312', 'Environment and Conservation Organizations', 'Environmental orgs', 'Membership Organizations', '81'),
('813319', 'Other Social Advocacy Organizations', 'Advocacy organizations', 'Membership Organizations', '81'),
('813410', 'Civic and Social Organizations', 'Civic organizations', 'Membership Organizations', '81'),
('813910', 'Business Associations', 'Business associations', 'Membership Organizations', '81'),
('813920', 'Professional Organizations', 'Professional associations', 'Membership Organizations', '81'),
('813930', 'Labor Unions and Similar Labor Organizations', 'Labor unions', 'Membership Organizations', '81'),
('813940', 'Political Organizations', 'Political parties', 'Membership Organizations', '81'),
('813990', 'Other Similar Organizations', 'Other membership orgs', 'Membership Organizations', '81'),
('814110', 'Private Households', 'Private households', 'Private Households', '81')
ON CONFLICT (code) DO NOTHING;