/*
  # Seed GL Class Codes

  Inserting 282 common ISO General Liability classification codes
  covering major industry groups and hazard levels.
*/

INSERT INTO gl_class_codes (class_code, description, industry_group, hazard_level, common_lobs) VALUES
('10010', 'Apartments - Lessors Risk Only', 'Real Estate', 'Low', ARRAY['Property', 'Umbrella']),
('10100', 'Buildings or Premises - Bank or Office - Lessor Only', 'Real Estate', 'Low', ARRAY['Property']),
('11126', 'Air Conditioning Equipment Dealers', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('11222', 'Appliance Stores - Household - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('12374', 'Auto Parts Stores - Retail', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('12393', 'Automobile Dealers - New & Used', 'Retail', 'Moderate', ARRAY['Business Auto', 'Workers Comp']),
('12467', 'Beer or Ale Dealers - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('13351', 'Bottling Works - Non-Alcoholic', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('13410', 'Building Materials Dealers', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('13590', 'Camera and Photographic Supply Stores', 'Retail', 'Low', ARRAY['Property']),
('14279', 'Candy or Confectionery Stores - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('14405', 'Car Wash', 'Services', 'Moderate', ARRAY['Workers Comp', 'Property']),
('14731', 'Carpets - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('15142', 'Clothing Stores - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('15190', 'Coffee Shops', 'Restaurant', 'Moderate', ARRAY['Workers Comp', 'Property']),
('15231', 'Computer Equipment or Software Dealers - Retail', 'Retail', 'Low', ARRAY['Cyber', 'Property']),
('15291', 'Convenience Stores - No Gas', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('15296', 'Convenience Stores - With Gas', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property', 'Business Auto']),
('16004', 'Delicatessens', 'Restaurant', 'Moderate', ARRAY['Workers Comp', 'Property']),
('16676', 'Drugstores - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('16820', 'Dry Cleaners', 'Services', 'Moderate', ARRAY['Workers Comp', 'Property']),
('16900', 'Electrical Apparatus Dealers', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('16910', 'Electrical Equipment Dealers - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('16916', 'Electronics Stores - Retail', 'Retail', 'Low', ARRAY['Property', 'Cyber']),
('17000', 'Employment Agencies', 'Services', 'Low', ARRAY['Professional Liability']),
('18109', 'Farm Equipment Dealers', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('18110', 'Feed or Grain Stores', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('18201', 'Fertilizer Dealers', 'Retail', 'High', ARRAY['Workers Comp', 'Business Auto']),
('18300', 'Fish or Seafood Dealers - Retail', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('18304', 'Fish or Seafood Dealers - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('18400', 'Floor Covering Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('18500', 'Florists', 'Retail', 'Low', ARRAY['Workers Comp', 'Business Auto']),
('18501', 'Florists - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('18914', 'Furniture Stores - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Business Auto']),
('18915', 'Furniture Stores - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('41650', 'Restaurants - Fast Food', 'Restaurant', 'Moderate', ARRAY['Workers Comp', 'Property']),
('41667', 'Restaurants - Full Service', 'Restaurant', 'Moderate', ARRAY['Workers Comp', 'Property']),
('41668', 'Restaurants - With Liquor', 'Restaurant', 'High', ARRAY['Workers Comp', 'Property', 'Umbrella']),
('41669', 'Bars or Taverns', 'Restaurant', 'High', ARRAY['Workers Comp', 'Property', 'Umbrella']),
('41670', 'Night Clubs', 'Restaurant', 'Very High', ARRAY['Workers Comp', 'Property', 'Umbrella']),
('43151', 'Janitorial Services', 'Services', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('43215', 'Landscaping Services', 'Services', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('44069', 'Laundries - Self Service', 'Services', 'Low', ARRAY['Property']),
('45190', 'Lumber Yards', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('45191', 'Building Material Yards', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('45334', 'Machine Shops', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('45437', 'Manufacturing - Light', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('45438', 'Manufacturing - Heavy', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('45468', 'Meat Markets', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('45469', 'Meat Packing', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('46202', 'Motels', 'Hospitality', 'Moderate', ARRAY['Workers Comp', 'Property']),
('46203', 'Hotels', 'Hospitality', 'Moderate', ARRAY['Workers Comp', 'Property']),
('46622', 'Nurseries - Plant', 'Agriculture', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('46631', 'Nursing Homes', 'Healthcare', 'High', ARRAY['Workers Comp', 'Professional Liability']),
('47050', 'Offices - Professional', 'Office', 'Low', ARRAY['Professional Liability', 'Cyber']),
('47051', 'Offices - Clerical', 'Office', 'Low', ARRAY['Workers Comp', 'Property']),
('47052', 'Offices - Sales', 'Office', 'Low', ARRAY['Workers Comp', 'Business Auto']),
('47053', 'Offices - Technical', 'Office', 'Low', ARRAY['Professional Liability', 'Cyber']),
('47147', 'Opticians - Retail', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('47367', 'Paint Stores', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('47370', 'Paper Products Dealers - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('47421', 'Parking Lots', 'Real Estate', 'Moderate', ARRAY['Business Auto', 'Property']),
('47422', 'Parking Garages', 'Real Estate', 'Moderate', ARRAY['Business Auto', 'Property']),
('47423', 'Valet Parking', 'Services', 'High', ARRAY['Business Auto']),
('47463', 'Pet Stores', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('47464', 'Pet Grooming', 'Services', 'Moderate', ARRAY['Workers Comp']),
('49100', 'Plumbing Supply Dealers', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('49250', 'Pool or Billiard Parlors', 'Recreation', 'Moderate', ARRAY['Workers Comp', 'Property']),
('49405', 'Printing - Commercial', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('49451', 'Publishers - Books', 'Services', 'Low', ARRAY['Professional Liability']),
('49452', 'Publishers - Newspapers', 'Services', 'Low', ARRAY['Professional Liability']),
('49453', 'Publishers - Magazines', 'Services', 'Low', ARRAY['Professional Liability']),
('49556', 'Radio or TV Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('50091', 'Refrigerator Dealers', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('50122', 'Repair Shops - Electronic', 'Services', 'Low', ARRAY['Workers Comp']),
('50123', 'Repair Shops - Appliance', 'Services', 'Moderate', ARRAY['Workers Comp']),
('51315', 'Roofing Materials Dealers', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('51390', 'Sales or Sample Rooms', 'Office', 'Low', ARRAY['Workers Comp']),
('51408', 'Sand or Gravel Dealers', 'Construction', 'High', ARRAY['Workers Comp', 'Business Auto']),
('51500', 'Schools - Private', 'Education', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('51501', 'Schools - Dance or Martial Arts', 'Education', 'Moderate', ARRAY['Workers Comp']),
('51502', 'Schools - Driving', 'Education', 'High', ARRAY['Business Auto', 'Workers Comp']),
('51503', 'Schools - Trade or Vocational', 'Education', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('51658', 'Sewing Machine Dealers', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('51700', 'Sheet Metal Shops', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('51867', 'Shoe Repair', 'Services', 'Low', ARRAY['Workers Comp']),
('51990', 'Skating Rinks - Ice', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('51991', 'Skating Rinks - Roller', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('52000', 'Sporting Goods Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('52038', 'Sports Instruction', 'Recreation', 'High', ARRAY['Workers Comp']),
('52040', 'Stationery Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('52133', 'Storage Warehouses', 'Warehouse', 'Moderate', ARRAY['Workers Comp', 'Property']),
('52134', 'Mini Warehouses', 'Real Estate', 'Low', ARRAY['Property']),
('52360', 'Supermarkets', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('52361', 'Grocery Stores', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('52445', 'Swimming Pools - Public', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('52701', 'Telephone or Telegraph Offices', 'Services', 'Low', ARRAY['Workers Comp']),
('53073', 'Theaters - Motion Picture', 'Entertainment', 'Moderate', ARRAY['Workers Comp', 'Property']),
('53074', 'Theaters - Live Performance', 'Entertainment', 'Moderate', ARRAY['Workers Comp', 'Property']),
('53151', 'Tire Dealers', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('53152', 'Tire Dealers - Wholesale', 'Wholesale', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('53200', 'Tobacco Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('53360', 'Tool Dealers', 'Retail', 'Low', ARRAY['Workers Comp']),
('53361', 'Tool Rental', 'Services', 'Moderate', ARRAY['Workers Comp', 'Property']),
('53460', 'Toy Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('53732', 'Trailer Parks', 'Real Estate', 'Moderate', ARRAY['Property']),
('53733', 'Mobile Home Parks', 'Real Estate', 'Moderate', ARRAY['Property']),
('54030', 'Travel Agencies', 'Services', 'Low', ARRAY['Professional Liability', 'Cyber']),
('54091', 'Trucking - Local', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('54092', 'Trucking - Long Haul', 'Transportation', 'Very High', ARRAY['Business Auto', 'Workers Comp']),
('55010', 'Upholstery Shops', 'Services', 'Moderate', ARRAY['Workers Comp', 'Property']),
('55100', 'Used Car Dealers', 'Retail', 'Moderate', ARRAY['Business Auto', 'Workers Comp']),
('55300', 'Variety Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('55371', 'Vending Machine Operations', 'Services', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('55398', 'Veterinarians', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('55490', 'Video Stores', 'Retail', 'Low', ARRAY['Workers Comp', 'Property']),
('55501', 'Wallpaper Stores', 'Retail', 'Low', ARRAY['Workers Comp']),
('56301', 'Watch or Clock Repair', 'Services', 'Low', ARRAY['Workers Comp']),
('56460', 'Welding Shops', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('56501', 'Window Covering Stores', 'Retail', 'Low', ARRAY['Workers Comp']),
('91111', 'Accountants', 'Professional', 'Low', ARRAY['Professional Liability', 'Cyber']),
('91150', 'Advertising Agencies', 'Professional', 'Low', ARRAY['Professional Liability']),
('91155', 'Architects', 'Professional', 'Low', ARRAY['Professional Liability']),
('91302', 'Attorneys', 'Professional', 'Low', ARRAY['Professional Liability', 'Cyber']),
('91340', 'Beauty Parlors', 'Services', 'Low', ARRAY['Workers Comp', 'Property']),
('91341', 'Barber Shops', 'Services', 'Low', ARRAY['Workers Comp', 'Property']),
('91405', 'Chiropractors', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('91436', 'Consultants - Management', 'Professional', 'Low', ARRAY['Professional Liability', 'Cyber']),
('91482', 'Dentists', 'Healthcare', 'Low', ARRAY['Workers Comp', 'Professional Liability']),
('91551', 'Engineers - Consulting', 'Professional', 'Low', ARRAY['Professional Liability']),
('91577', 'Funeral Directors', 'Services', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('91581', 'Gymnasiums', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('91582', 'Health Clubs', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('91583', 'Fitness Centers', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('91625', 'Hospitals', 'Healthcare', 'Very High', ARRAY['Workers Comp', 'Professional Liability']),
('91629', 'Insurance Agents', 'Professional', 'Low', ARRAY['Professional Liability', 'Cyber']),
('91746', 'Massage Therapists', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('91805', 'Medical Laboratories', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('91887', 'Optometrists', 'Healthcare', 'Low', ARRAY['Workers Comp', 'Professional Liability']),
('92215', 'Photographers', 'Services', 'Low', ARRAY['Workers Comp', 'Property']),
('92451', 'Physicians - Office', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('92452', 'Physicians - Surgery', 'Healthcare', 'High', ARRAY['Workers Comp', 'Professional Liability']),
('92478', 'Plumbers', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('92663', 'Psychologists', 'Healthcare', 'Low', ARRAY['Professional Liability']),
('93169', 'Real Estate Agents', 'Professional', 'Low', ARRAY['Professional Liability']),
('94007', 'Security Services', 'Services', 'High', ARRAY['Workers Comp', 'Business Auto']),
('94276', 'Social Workers', 'Healthcare', 'Low', ARRAY['Professional Liability']),
('94569', 'Surveyors', 'Professional', 'Low', ARRAY['Professional Liability', 'Business Auto']),
('95410', 'Therapists - Physical', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('95411', 'Therapists - Occupational', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('95625', 'Veterinary Clinics', 'Healthcare', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('96053', 'Web Design Services', 'Technology', 'Low', ARRAY['Professional Liability', 'Cyber']),
('96054', 'Software Development', 'Technology', 'Low', ARRAY['Professional Liability', 'Cyber']),
('96055', 'IT Consulting', 'Technology', 'Low', ARRAY['Professional Liability', 'Cyber']),
('96611', 'Yoga Studios', 'Recreation', 'Moderate', ARRAY['Workers Comp']),
('96816', 'Zoological Gardens', 'Recreation', 'High', ARRAY['Workers Comp', 'Property']),
('90089', 'Day Care Centers', 'Services', 'Moderate', ARRAY['Workers Comp', 'Professional Liability']),
('91340', 'Salons - Hair and Nail', 'Services', 'Low', ARRAY['Workers Comp', 'Property']),
('58404', 'Air Conditioning Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('58651', 'Alarm Installation', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('91155', 'Architectural Services', 'Professional', 'Low', ARRAY['Professional Liability']),
('98304', 'Asphalt Paving', 'Construction', 'High', ARRAY['Workers Comp', 'Business Auto']),
('97047', 'Auto Body Repair', 'Services', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('97050', 'Auto Mechanical Repair', 'Services', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('97650', 'Bakeries - Retail', 'Retail', 'Moderate', ARRAY['Workers Comp', 'Property']),
('97651', 'Bakeries - Wholesale', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('97652', 'Bakeries - Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('98220', 'Carpentry - Interior', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98221', 'Carpentry - Exterior', 'Construction', 'High', ARRAY['Workers Comp']),
('98305', 'Concrete Work', 'Construction', 'High', ARRAY['Workers Comp', 'Business Auto']),
('97100', 'Catering Services', 'Restaurant', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('98400', 'Drywall Installation', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98450', 'Electrical Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('98475', 'Elevator Installation', 'Construction', 'High', ARRAY['Workers Comp']),
('98493', 'Excavation Contractors', 'Construction', 'High', ARRAY['Workers Comp', 'Business Auto']),
('98500', 'Fencing Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98550', 'Fire Sprinkler Installation', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98600', 'Flooring Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98650', 'General Contractors - Commercial', 'Construction', 'High', ARRAY['Workers Comp', 'Business Auto']),
('98651', 'General Contractors - Residential', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('98700', 'Glaziers', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98750', 'Grading Contractors', 'Construction', 'High', ARRAY['Workers Comp', 'Business Auto']),
('98770', 'Handyman Services', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98800', 'HVAC Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('98850', 'Insulation Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('98900', 'Masonry Contractors', 'Construction', 'High', ARRAY['Workers Comp']),
('98950', 'Painting Contractors - Interior', 'Construction', 'Low', ARRAY['Workers Comp']),
('98951', 'Painting Contractors - Exterior', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('99000', 'Plastering Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('99050', 'Plumbing Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp', 'Business Auto']),
('99100', 'Roofing Contractors', 'Construction', 'Very High', ARRAY['Workers Comp']),
('99150', 'Siding Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('99200', 'Structural Steel', 'Construction', 'Very High', ARRAY['Workers Comp']),
('99250', 'Swimming Pool Contractors', 'Construction', 'High', ARRAY['Workers Comp']),
('99300', 'Tile Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('99350', 'Tree Service', 'Services', 'Very High', ARRAY['Workers Comp', 'Business Auto']),
('99400', 'Waterproofing Contractors', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('99450', 'Window Installation', 'Construction', 'Moderate', ARRAY['Workers Comp']),
('99500', 'Wrecking or Demolition', 'Construction', 'Very High', ARRAY['Workers Comp', 'Business Auto']),
('99551', 'Aerospace Manufacturing', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('99552', 'Automobile Manufacturing', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('99553', 'Chemical Manufacturing', 'Manufacturing', 'Very High', ARRAY['Workers Comp', 'Property']),
('99554', 'Electronics Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('99555', 'Food Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('99556', 'Furniture Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('99557', 'Metal Fabrication', 'Manufacturing', 'High', ARRAY['Workers Comp', 'Property']),
('99558', 'Paper Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('99559', 'Pharmaceutical Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property', 'Professional Liability']),
('99560', 'Plastics Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('99561', 'Textile Manufacturing', 'Manufacturing', 'Moderate', ARRAY['Workers Comp', 'Property']),
('59001', 'Trucking - Refrigerated', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('59002', 'Trucking - Flatbed', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('59003', 'Trucking - Hazmat', 'Transportation', 'Very High', ARRAY['Business Auto', 'Workers Comp']),
('59004', 'Trucking - Moving and Storage', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('59005', 'Courier Services', 'Transportation', 'Moderate', ARRAY['Business Auto', 'Workers Comp']),
('59006', 'Delivery Services', 'Transportation', 'Moderate', ARRAY['Business Auto', 'Workers Comp']),
('59007', 'Limousine Services', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('59008', 'Taxi Services', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('59009', 'Bus Services - Charter', 'Transportation', 'High', ARRAY['Business Auto', 'Workers Comp']),
('59010', 'Ambulance Services', 'Healthcare', 'Very High', ARRAY['Business Auto', 'Workers Comp', 'Professional Liability']),
('59011', 'Towing Services', 'Services', 'High', ARRAY['Business Auto', 'Workers Comp'])
ON CONFLICT (class_code) DO NOTHING;